# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PekrVKMoxVavpIYX5dXSEXZ8bnIF6M5s
"""

# app.py
import numpy as np
from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import joblib

# =========================
# Load trained model
# =========================
MODEL_PATH = "bank_marketing_model.pkl"
model = joblib.load(MODEL_PATH)

# =========================
# Initialize FastAPI
# =========================
app = FastAPI(
    title="Bank Marketing Prediction API",
    description="Predict whether a customer will subscribe to a term deposit",
    version="1.0"
)

# =========================
# Input schema
# =========================
class CustomerInput(BaseModel):
    age: int
    job: str
    marital: str
    education: str
    default: str
    housing: str
    loan: str
    contact: str
    month: str
    day_of_week: str
    duration: int
    campaign: int
    pdays: int
    previous: int
    poutcome: str
    emp_var_rate: float
    cons_price_idx: float
    cons_conf_idx: float
    euribor3m: float
    nr_employed: float

# =========================
# Root endpoint
# =========================
@app.get("/")
def home():
    return {"message": "Bank Marketing Model API is running 🚀"}

# =========================
# Prediction endpoint
# =========================
@app.post("/predict")
def predict(data: CustomerInput):
    input_df = pd.DataFrame([{
        "age": data.age,
        "job": data.job,
        "marital": data.marital,
        "education": data.education,
        "default": data.default,
        "housing": data.housing,
        "loan": data.loan,
        "contact": data.contact,
        "month": data.month,
        "day_of_week": data.day_of_week,
        "duration": data.duration,
        "campaign": data.campaign,
        "pdays": data.pdays,
        "previous": data.previous,
        "poutcome": data.poutcome,
        "emp.var.rate": data.emp_var_rate,
        "cons.price.idx": data.cons_price_idx,
        "cons.conf.idx": data.cons_conf_idx,
        "euribor3m": data.euribor3m,
        "nr.employed": data.nr_employed
    }])

    # Feature engineering
    input_df["previously_contacted"] = (input_df["pdays"] != 999).astype(int)
    input_df["duration_log"] = np.log1p(input_df["duration"])

    # Prediction
    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1]

    return {
        "subscription_prediction": int(prediction),
        "subscription_probability": round(float(probability), 4)
    }